/* Florida P&C Market Explorer — frontend logic.
   Pure client-side; reads window.FL_DATA (generated by etl/ingest.py).
   Three views over the normalized Type-B fact table:
     rank   — single-quarter carrier ranking by a metric
     share  — market share of a metric within the filtered slice
     series — multi-carrier time series (also covers comparison), with
              optional QoQ / YoY transforms.
*/
(function () {
"use strict";

const D = window.FL_DATA;
if (!D) { document.body.innerHTML = "<p style='padding:20px'>data.js not found — run update.bat.</p>"; return; }

// ---------- ordered period list ---------------------------------------- //
const periodKey = p => (parseInt(p.slice(0,4),10)*10) + parseInt(p.slice(-1),10);
const PERIODS = D.periods.map(x=>x.period).sort((a,b)=>periodKey(a)-periodKey(b));
const PERIOD_META = Object.fromEntries(D.periods.map(p=>[p.period,p]));

// ---------- metric catalog --------------------------------------------- //
// kind: money | count | pct ; wind: has _excl_wind/_incl_wind columns
// derived: computed from component sums (see aggregate())
const METRICS = [
  {id:"pif",                 label:"Policies in force (PIF)",        kind:"count", wind:true},
  {id:"tiv",                 label:"Exposure / TIV ($)",            kind:"money", wind:true},
  {id:"dpw",                 label:"Direct premium written ($)",     kind:"money", wind:true},
  {id:"new_written",         label:"New policies written",           kind:"count"},
  {id:"received_in",         label:"Received (takeout / assumption)",kind:"count"},
  {id:"cancelled",           label:"Policies cancelled",             kind:"count"},
  {id:"cancelled_hurricane", label:"Cancelled — hurricane risk",     kind:"count"},
  {id:"nonrenewed",          label:"Policies nonrenewed",            kind:"count"},
  {id:"nonrenewed_hurricane",label:"Nonrenewed — hurricane risk",    kind:"count"},
  {id:"transferred_out",     label:"Transferred to other insurers",  kind:"count"},
  {id:"claims_opened",       label:"Claims opened",                  kind:"count"},
  {id:"claims_closed",       label:"Claims closed",                  kind:"count"},
  {id:"claims_pending",      label:"Claims pending",                 kind:"count"},
  {id:"lawsuits_opened",     label:"Lawsuits opened",                kind:"count"},
  {id:"lawsuits_closed",     label:"Lawsuits closed",                kind:"count"},
  {id:"lawsuits_closed_consumer", label:"Lawsuits closed (for consumer)", kind:"count"},
  // ---- derived (R11) ----
  {id:"net_flow",            label:"⊕ Net policy flow",              kind:"count", derived:true},
  {id:"avg_premium",         label:"⊕ Avg premium / policy ($)",     kind:"money", derived:true, ratio:true},
  {id:"rate_on_line",        label:"⊕ Rate-on-line (DPW/TIV)",       kind:"pct",   derived:true, ratio:true},
  {id:"wind_concentration",  label:"⊕ Wind concentration (incl/total TIV)", kind:"pct", derived:true, ratio:true},
];
const METRIC = Object.fromEntries(METRICS.map(m=>[m.id,m]));
// only base metrics that actually appear in the data
const AVAIL = new Set(D.metrics_b);

// ---------- state ------------------------------------------------------ //
const S = {
  mode:"rank", metric:"tiv", wind:"all", line:"all",
  windOnlyOnly:false, policyTypes:new Set(),
  periodSingle:PERIODS[PERIODS.length-1],
  periodFrom:PERIODS[Math.max(0,PERIODS.length-9)], periodTo:PERIODS[PERIODS.length-1],
  companies:new Set(), scale:"auto", topn:20, transform:"abs",
  sortCol:null, sortDir:-1,
};

// ============ helpers =================================================== //
const $ = s => document.querySelector(s);
const sum = (arr,f) => { let s=0; for(const x of arr){const v=x[f]; if(v!=null) s+=v;} return s; };

// column for a wind-enabled metric given the wind-basis selector
function metricCol(metricId, wind){
  const m=METRIC[metricId];
  if(!m || !m.wind || wind==="all") return metricId;
  const c = metricId + (wind==="excl"?"_excl_wind":"_incl_wind");
  return AVAIL.has(c)? c : metricId;
}

// filter the Type-B facts for one period by line / policy-type / wind-only
function filterFacts(period){
  const lineAll = S.line==="all";
  const usePT = S.policyTypes.size>0;
  const out=[];
  for(const f of D.facts_b){
    if(f.p!==period) continue;
    if(!lineAll && f.line!==S.line) continue;
    if(S.windOnlyOnly && !f.wind_only) continue;
    if(usePT && !S.policyTypes.has(f.pt)) continue;
    out.push(f);
  }
  return out;
}

// aggregate filtered facts into per-NAIC values for a metric
function aggregate(facts, metricId, wind){
  const m=METRIC[metricId];
  const by={};                       // naic -> accumulator
  const get=naic=>by[naic]||(by[naic]={naic, company:D.companies[naic]?.name||naic});
  if(m.derived){
    for(const f of facts){
      const a=get(f.naic);
      a.dpw=(a.dpw||0)+(f.dpw||0); a.pif=(a.pif||0)+(f.pif||0);
      a.tiv=(a.tiv||0)+(f.tiv||0); a.tiv_incl=(a.tiv_incl||0)+(f.tiv_incl_wind||0);
      a.nw=(a.nw||0)+(f.new_written||0); a.ri=(a.ri||0)+(f.received_in||0);
      a.cn=(a.cn||0)+(f.cancelled||0); a.nr=(a.nr||0)+(f.nonrenewed||0);
      a.to=(a.to||0)+(f.transferred_out||0);
    }
    for(const naic in by){const a=by[naic];
      if(metricId==="net_flow")          a.value=a.nw+a.ri-a.cn-a.nr-a.to;
      else if(metricId==="avg_premium")  a.value=a.pif? a.dpw/a.pif : null;
      else if(metricId==="rate_on_line") a.value=a.tiv? a.dpw/a.tiv : null;
      else if(metricId==="wind_concentration") a.value=a.tiv? a.tiv_incl/a.tiv : null;
    }
  } else {
    const col=metricCol(metricId,wind);
    for(const f of facts){ const a=get(f.naic); const v=f[col]; if(v!=null) a.value=(a.value||0)+v; }
  }
  return by;
}

// scalar aggregate over a whole filtered slice (statewide rollup)
function aggregateTotal(facts, metricId, wind){
  const m=METRIC[metricId];
  if(m.derived){
    const t={dpw:sum(facts,"dpw"),pif:sum(facts,"pif"),tiv:sum(facts,"tiv"),
      tiv_incl:sum(facts,"tiv_incl_wind"),nw:sum(facts,"new_written"),
      ri:sum(facts,"received_in"),cn:sum(facts,"cancelled"),nr:sum(facts,"nonrenewed"),
      to:sum(facts,"transferred_out")};
    if(metricId==="net_flow") return t.nw+t.ri-t.cn-t.nr-t.to;
    if(metricId==="avg_premium") return t.pif? t.dpw/t.pif:null;
    if(metricId==="rate_on_line") return t.tiv? t.dpw/t.tiv:null;
    if(metricId==="wind_concentration") return t.tiv? t.tiv_incl/t.tiv:null;
  }
  return sum(facts, metricCol(metricId,wind));
}

// ---------- formatting ------------------------------------------------- //
function fmt(v, metricId){
  if(v==null) return '<span class="sup">—</span>';
  const m=METRIC[metricId];
  if(m.kind==="pct") return (v*100).toFixed(1)+"%";
  if(m.kind==="money"){
    let div=1,suf="";
    if(S.scale==="auto"){const a=Math.abs(v);
      if(a>=1e12){div=1e12;suf="T";}else if(a>=1e9){div=1e9;suf="B";}
      else if(a>=1e6){div=1e6;suf="M";}else if(a>=1e3){div=1e3;suf="K";}}
    else {div=+S.scale; suf={1:"",1000:"K",1000000:"M",1000000000:"B"}[S.scale]||"";}
    const n=v/div;
    return "$"+n.toLocaleString(undefined,{maximumFractionDigits: suf?2:0})+suf;
  }
  return Math.round(v).toLocaleString();
}
const pct1 = x => (x==null?'<span class="sup">—</span>':(x>=0?"+":"")+x.toFixed(1)+"%");

// ============ rendering ================================================ //
function render(){
  syncControlsVisibility();
  if(S.mode==="series") renderSeries();
  else renderSnapshot();           // rank + share share a table/bar
  renderContext();
}

// ----- snapshot (rank / share) ----------------------------------------- //
let lastTable=null;                  // {headers, rows, csvRows} for export
function renderSnapshot(){
  const period=S.periodSingle;
  const facts=filterFacts(period);
  const by=aggregate(facts, S.metric, S.wind);
  let rows=Object.values(by).filter(r=>r.value!=null);
  const total=rows.reduce((s,r)=>s+(r.value||0),0);
  rows.sort((a,b)=>(b.value||0)-(a.value||0));

  const isShare=S.mode==="share";
  const topn=+S.topn;
  let shown=rows.slice(0,topn);
  let othersVal=0;
  if(isShare && rows.length>topn){ othersVal=rows.slice(topn).reduce((s,r)=>s+(r.value||0),0); }

  // table
  const headers=[{k:"rank",t:"#",cls:""},{k:"company",t:"Company",cls:"l"},
    {k:"naic",t:"NAIC",cls:"l"},{k:"value",t:METRIC[S.metric].label,cls:""}];
  if(isShare) headers.push({k:"share",t:"Share",cls:""});
  const trows=shown.map((r,i)=>({
    rank:i+1, company:r.company, naic:r.naic, value:r.value,
    share: total? r.value/total : null
  }));
  if(isShare && othersVal>0) trows.push({rank:"", company:"All others", naic:"", value:othersVal, share: total?othersVal/total:null});

  // apply column sort if user clicked a header
  if(S.sortCol){
    trows.sort((a,b)=>{const x=a[S.sortCol],y=b[S.sortCol];
      if(typeof x==="number"||typeof y==="number") return ((x||0)-(y||0))*S.sortDir;
      return String(x).localeCompare(String(y))*S.sortDir;});
  }

  drawTable(headers, trows);
  $("#tableTitle").textContent=`${rows.length} carriers · ${period} · published statewide total = ${fmtPlain(total)}`;

  // chart: horizontal bar of top-N. automargin lets Plotly size the left gutter
  // to the (truncated) carrier names so they're never clipped on wide screens.
  const bar=shown.slice().reverse();
  const data=[{type:"bar",orientation:"h",
    y:bar.map(r=>shortName(r.company)), x:bar.map(r=>r.value),
    marker:{color:"#4ea1ff"},
    hovertemplate:"%{y}<br>"+METRIC[S.metric].label+": %{x:,.0f}<extra></extra>"}];
  plot(data, {title:`${isShare?"Market share — ":""}${METRIC[S.metric].label} · ${period}`,
    margin:{l:8,r:24,t:48,b:40},
    yaxis:{automargin:true, tickfont:{size:10}},
    height:Math.min(540, Math.max(300, bar.length*18+90))});
}

// ----- time series ----------------------------------------------------- //
function renderSeries(){
  const from=periodKey(S.periodFrom), to=periodKey(S.periodTo);
  const range=PERIODS.filter(p=>periodKey(p)>=Math.min(from,to)&&periodKey(p)<=Math.max(from,to));
  const naics=[...S.companies];
  const series=[];                   // {name, naic, vals:[{p,v}]}
  const ALL="__ALL__";
  const targets = naics.length? naics : [ALL];

  for(const key of targets){
    const vals=range.map(p=>{
      const facts=filterFacts(p);
      let v;
      if(key===ALL) v=aggregateTotal(facts,S.metric,S.wind);
      else { const by=aggregate(facts,S.metric,S.wind); v=by[key]?by[key].value:null; }
      return {p, v};
    });
    const name = key===ALL ? "★ All carriers (filtered slice)" : (D.companies[key]?.name||key);
    series.push({name, naic:key, vals});
  }

  // transform
  const tf=S.transform;
  const disp=series.map(s=>{
    let vv=s.vals.map(x=>x.v);
    if(tf==="qoq") vv=vv.map((v,i)=> i>0&&v!=null&&s.vals[i-1].v? (v-s.vals[i-1].v)/s.vals[i-1].v*100 : (i===0?null:null));
    if(tf==="yoy") vv=vv.map((v,i)=> i>=4&&v!=null&&s.vals[i-4].v? (v-s.vals[i-4].v)/s.vals[i-4].v*100 : null);
    return {...s, disp:vv};
  });

  // chart
  const data=disp.map(s=>({type:"scatter",mode:"lines+markers",name:shortName(s.name),
    x:range, y:s.disp,
    hovertemplate:"%{x}<br>"+shortName(s.name)+": "+(tf==="abs"?"%{y:,.0f}":"%{y:.1f}%")+"<extra></extra>"}));
  const ytitle = tf==="abs"?METRIC[S.metric].label:(tf==="qoq"?"QoQ %":"YoY %");
  plot(data,{title:`${METRIC[S.metric].label} over time`, margin:{l:80,r:20,t:40,b:50},
    height:430, yaxis:{title:ytitle}, xaxis:{title:""}});

  // table: periods as rows, series as columns
  const headers=[{k:"period",t:"Period",cls:"l"}];
  disp.forEach((s,i)=>headers.push({k:"c"+i,t:shortName(s.name),cls:""}));
  const trows=range.map((p,ri)=>{
    const row={period:p};
    disp.forEach((s,i)=>row["c"+i]= tf==="abs"? s.disp[ri] : s.disp[ri]);
    return row;
  });
  drawTable(headers, trows, tf!=="abs");
  $("#tableTitle").textContent=`${targets.length} series · ${range[0]} → ${range[range.length-1]} · ${tf==="abs"?"absolute":tf.toUpperCase()}`;
}

// ----- generic table + CSV --------------------------------------------- //
function drawTable(headers, rows, pctMode){
  const thead=$("#tbl thead"), tbody=$("#tbl tbody");
  thead.innerHTML="<tr>"+headers.map(h=>`<th class="${h.cls}" data-k="${h.k}">${h.t}</th>`).join("")+"</tr>";
  const body=rows.map(r=>"<tr>"+headers.map(h=>{
    const v=r[h.k];
    if(h.k==="company"||h.k==="naic"||h.k==="period") return `<td class="l">${v??""}</td>`;
    if(h.k==="rank") return `<td>${v??""}</td>`;
    if(h.k==="share") return `<td class="num">${v==null?'<span class="sup">—</span>':(v*100).toFixed(1)+"%"}</td>`;
    // value-ish numeric
    if(pctMode) return `<td class="num">${pct1(v)}</td>`;
    return `<td class="num">${fmt(v, S.metric)}</td>`;
  }).join("")+"</tr>").join("");
  tbody.innerHTML=body;
  // header click → sort (snapshot only)
  thead.querySelectorAll("th").forEach(th=>th.onclick=()=>{
    const k=th.dataset.k; if(S.mode==="series") return;
    if(S.sortCol===k) S.sortDir*=-1; else {S.sortCol=k; S.sortDir=(k==="company"||k==="naic")?1:-1;}
    render();
  });
  // stash for CSV
  lastTable={headers, rows, pctMode};
}

function exportCSV(){
  if(!lastTable) return;
  const {headers,rows,pctMode}=lastTable;
  const esc=s=>{s=String(s??"");return /[",\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s;};
  const lines=[headers.map(h=>esc(h.t)).join(",")];
  for(const r of rows){
    lines.push(headers.map(h=>{
      const v=r[h.k];
      if(typeof v==="number" && h.k!=="rank") return v;     // raw precision in CSV
      return esc(v);
    }).join(","));
  }
  const blob=new Blob([lines.join("\n")],{type:"text/csv"});
  const a=document.createElement("a"); a.href=URL.createObjectURL(blob);
  a.download=`florida_pc_${S.mode}_${S.metric}_${Date.now()}.csv`; a.click();
}

// ---------- chart wrapper ---------------------------------------------- //
function plot(data, layout){
  Plotly.react($("#chart"), data, Object.assign({
    paper_bgcolor:"#171a21", plot_bgcolor:"#171a21",
    font:{color:"#cfd6e2",size:12}, showlegend:S.mode==="series",
    legend:{orientation:"h",y:-0.18},
    xaxis:{gridcolor:"#262b35"}, yaxis:{gridcolor:"#262b35"},
  }, layout), {displayModeBar:false, responsive:true});
}

// ---------- context bar ------------------------------------------------ //
function renderContext(){
  const c=[];
  c.push(`<span class="pill">View <b>${ {rank:"Ranking",share:"Market share",series:"Time series"}[S.mode] }</b></span>`);
  c.push(`<span class="pill">Metric <b>${METRIC[S.metric].label}</b></span>`);
  if(METRIC[S.metric].wind) c.push(`<span class="pill">Wind <b>${ {all:"all",incl:"incl",excl:"excl"}[S.wind] }</b></span>`);
  c.push(`<span class="pill">Line <b>${S.line==="all"?"all":S.line.split(" ")[0]}</b></span>`);
  if(S.windOnlyOnly) c.push(`<span class="pill">wind-only types</span>`);
  if(S.policyTypes.size) c.push(`<span class="pill">${S.policyTypes.size} policy type(s)</span>`);
  if(S.mode==="series"){
    c.push(`<span class="pill">${S.periodFrom} → ${S.periodTo}</span>`);
    c.push(`<span class="pill">${S.companies.size||"all"} carrier(s)</span>`);
    if(S.transform!=="abs") c.push(`<span class="pill"><b>${S.transform.toUpperCase()}</b></span>`);
  } else {
    c.push(`<span class="pill">Period <b>${S.periodSingle}</b></span>`);
  }
  $("#ctx").innerHTML=c.join("");
}

// ---------- misc fmt helpers ------------------------------------------- //
function fmtPlain(v){ const s=S.scale; S.scale="auto"; const o=fmt(v,S.metric); S.scale=s; return o.replace(/<[^>]+>/g,""); }
function shortName(n){ return n.length>34? n.slice(0,32)+"…" : n; }

// ============ control wiring =========================================== //
function buildControls(){
  // coverage line
  const a=PERIODS[0], b=PERIODS[PERIODS.length-1];
  $("#coverage").textContent=`${PERIODS.length} quarters · ${a} → ${b} · ${Object.keys(D.companies).length} carriers`;
  $("#genAt").textContent=(D.generated_at||"").replace("T"," ");

  // metric select (skip metrics with no data)
  const msel=$("#metric");
  msel.innerHTML=METRICS.filter(m=>m.derived||AVAIL.has(m.id))
    .map(m=>`<option value="${m.id}" ${m.id===S.metric?"selected":""}>${m.label}</option>`).join("");
  msel.onchange=()=>{S.metric=msel.value; S.sortCol=null; updateWindState(); render();};

  // period selects
  const opts=PERIODS.map(p=>`<option value="${p}">${p}</option>`).join("");
  for(const id of ["periodSingle","periodFrom","periodTo"]) $("#"+id).innerHTML=opts;
  $("#periodSingle").value=S.periodSingle; $("#periodFrom").value=S.periodFrom; $("#periodTo").value=S.periodTo;
  $("#periodSingle").onchange=e=>{S.periodSingle=e.target.value;render();};
  $("#periodFrom").onchange=e=>{S.periodFrom=e.target.value;render();};
  $("#periodTo").onchange=e=>{S.periodTo=e.target.value;render();};

  // segmented buttons
  segWire("#modeSeg","mode","mode",()=>{S.sortCol=null;});
  segWire("#windSeg","w","wind");
  segWire("#lineSeg","line","line",()=>{S.policyTypes.clear(); buildPolicyTypes();});
  segWire("#transformSeg","t","transform");

  $("#windOnlyOnly").onchange=e=>{S.windOnlyOnly=e.target.checked;render();};

  // policy types
  $("#ptSearch").oninput=buildPolicyTypes;
  buildPolicyTypes();

  // companies
  $("#coSearch").oninput=buildCompanies;
  buildCompanies();

  // display selects
  $("#scale").onchange=e=>{S.scale=e.target.value;render();};
  $("#topn").onchange=e=>{S.topn=e.target.value;render();};
  $("#csvBtn").onclick=exportCSV;

  updateWindState();
}

function segWire(sel, attr, stateKey, after){
  const seg=$(sel);
  seg.querySelectorAll("button").forEach(btn=>btn.onclick=()=>{
    seg.querySelectorAll("button").forEach(b=>b.classList.remove("on"));
    btn.classList.add("on");
    S[stateKey]=btn.dataset[attr];
    if(after) after();
    if(stateKey==="metric") updateWindState();
    render();
  });
}

function updateWindState(){
  const on=METRIC[S.metric].wind;
  $("#windSeg").style.opacity=on?1:0.4;
  $("#windSeg").style.pointerEvents=on?"auto":"none";
  if(!on){ S.wind="all"; $("#windSeg").querySelectorAll("button").forEach(b=>b.classList.toggle("on",b.dataset.w==="all")); }
}

function buildPolicyTypes(){
  const q=($("#ptSearch").value||"").toLowerCase();
  const sel=$("#policyTypes");
  const list=Object.values(D.policy_types)
    .filter(pt=>S.line==="all"||pt.line===S.line)
    .filter(pt=>!S.windOnlyOnly||pt.is_wind_only)
    .filter(pt=>pt.policy_type.toLowerCase().includes(q))
    .sort((x,y)=>x.policy_type.localeCompare(y.policy_type));
  sel.innerHTML=list.map(pt=>`<option value="${esc(pt.policy_type)}" ${S.policyTypes.has(pt.policy_type)?"selected":""}>${pt.is_wind_only?"〜 ":""}${ptShort(pt.policy_type)}</option>`).join("");
  $("#ptCount").textContent=S.policyTypes.size?`(${S.policyTypes.size})`:"";
  sel.onchange=()=>{S.policyTypes=new Set([...sel.selectedOptions].map(o=>o.value));$("#ptCount").textContent=S.policyTypes.size?`(${S.policyTypes.size})`:"";render();};
}

function buildCompanies(){
  const q=($("#coSearch").value||"").toLowerCase();
  const sel=$("#companies");
  const list=Object.values(D.companies)
    .filter(c=> !q || c.name.toLowerCase().includes(q) || c.naic.includes(q) || c.names.some(n=>n.toLowerCase().includes(q)))
    .sort((a,b)=>a.name.localeCompare(b.name));
  sel.innerHTML=list.map(c=>`<option value="${c.naic}" ${S.companies.has(c.naic)?"selected":""}>${shortName(c.name)} · ${c.naic}</option>`).join("");
  $("#coCount").textContent=S.companies.size?`(${S.companies.size})`:"(all)";
  sel.onchange=()=>{S.companies=new Set([...sel.selectedOptions].map(o=>o.value));$("#coCount").textContent=S.companies.size?`(${S.companies.size})`:"(all)";render();};
}

function syncControlsVisibility(){
  const series=S.mode==="series";
  $("#rangeRow").style.display=series?"flex":"none";
  $("#periodSingle").style.display=series?"none":"block";
  $("#periodLbl").textContent=series?"Period range":"Period";
  $("#companyGrp").style.opacity=series?1:0.5;
  $("#transformSeg").style.opacity=series?1:0.4;
  $("#transformSeg").style.pointerEvents=series?"auto":"none";
}

function ptShort(s){ return s.replace("Commercial Residential - ","C: ").replace("Personal Residential - ","P: "); }
function esc(s){ return String(s).replace(/"/g,"&quot;"); }

// ============ go ======================================================= //
buildControls();
render();
})();
